### ISSUE TITLE
Ne pas commit les données critiques

### ISSUE THREAD

**Issue by techerjeansebastienpro** [RunningTurtle1/blogJeanRochefort#1]
https://github.com/RunningTurtle1/blogJeanRochefort/blob/fc78b7740cc84591500b49dd0741dee2d545e6e1/model/connexionManager.php#L8

Tu peux extraire les identifiants et mots de passe, les placer dans un fichier non commit (voir .gitignore)

**Comment by RunningTurtle1** [comment]
fichier .gitignore créé
